# Generated by Django 4.2.28 on 2026-04-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('telegram', 'Telegram'), ('max', 'MAX')], default='email', max_length=16, verbose_name='Канал')),
                ('value', models.CharField(help_text='Email адрес или идентификатор канала (например chat_id).', max_length=255, verbose_name='Получатель')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Получатель уведомлений',
                'verbose_name_plural': 'Получатели уведомлений',
                'ordering': ['channel', 'value'],
            },
        ),
        migrations.AddConstraint(
            model_name='notificationrecipient',
            constraint=models.UniqueConstraint(fields=('channel', 'value'), name='pages_notification_recipient_channel_value_uq'),
        ),
    ]
