# Generated by Django 4.2.28 on 2026-04-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_notificationrecipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrecipient',
            name='bot_token',
            field=models.CharField(blank=True, help_text='Для Telegram: токен бота (если не указан, используется из .env).', max_length=255, verbose_name='Bot token'),
        ),
    ]
