# Generated by Django 4.2.28 on 2026-04-27 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_notificationrecipient_bot_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=16, verbose_name='Канал')),
                ('recipient', models.CharField(max_length=255, verbose_name='Получатель')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('failed', 'Ошибка'), ('skipped', 'Пропущено')], default='pending', max_length=16, verbose_name='Статус')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='Попыток')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('idempotency_key', models.CharField(max_length=255, unique=True, verbose_name='Idempotency key')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Время успешной отправки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to='pages.priceinquiry', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Лог доставки уведомления',
                'verbose_name_plural': 'Логи доставки уведомлений',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel', 'status'], name='pg_notif_del_ch_st_idx'), models.Index(fields=['inquiry', 'status'], name='pg_notif_del_inq_st_idx')],
            },
        ),
    ]
