# Generated by Django 4.2.28 on 2026-04-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_notificationdelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationRecipient',
            fields=[
            ],
            options={
                'verbose_name': 'Получатель Email',
                'verbose_name_plural': 'Получатели Email',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.notificationrecipient',),
        ),
        migrations.CreateModel(
            name='TelegramNotificationRecipient',
            fields=[
            ],
            options={
                'verbose_name': 'Получатель Telegram',
                'verbose_name_plural': 'Получатели Telegram',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.notificationrecipient',),
        ),
    ]
