# Generated by Django 4.2.28 on 2026-04-28 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_emailnotificationrecipient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramnotificationrecipient',
            options={'verbose_name': 'Телеграм канал / Телеграм Бот', 'verbose_name_plural': 'Телеграм канал / Телеграм Бот'},
        ),
    ]
