# Generated by Django 4.2.28 on 2026-04-28 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_telegramnotificationrecipient_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxNotificationRecipient',
            fields=[
            ],
            options={
                'verbose_name': 'MAX канал / MAX Бот',
                'verbose_name_plural': 'MAX канал / MAX Бот',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pages.notificationrecipient',),
        ),
    ]
