# Generated by Django 4.2.26 on 2026-08-16 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_remove_usefulcategory_use_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usefulpost',
            name='attachment_file',
            field=models.FileField(blank=True, help_text='PDF или другой документ для скачивания с страницы материала.', upload_to='useful_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])], verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='usefulpost',
            name='attachment_label',
            field=models.CharField(blank=True, help_text='Необязательно. Если пусто — на сайте будет «Скачать файл».', max_length=120, verbose_name='Подпись ссылки'),
        ),
    ]
