"""
Django settings for tir_lugansk project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Загрузка .env из папки с settings или из корня проекта
_env_file = Path(__file__).resolve().parent / '.env'
if not _env_file.exists():
    _env_file = BASE_DIR / '.env'
load_dotenv(_env_file)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Задаётся через переменную окружения DJANGO_SECRET_KEY (в .env или systemd).
# Для локальной разработки без .env используется небезопасный ключ — не для продакшена.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    SECRET_KEY = 'dev-insecure-key-do-not-use-in-production'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['45.130.42.65', 'new.tir-lugansk.ru', 'tir-lugansk.ru', 'localhost', '127.0.0.1']

# Админка только по этим хостам (None = не ограничивать). В продакшене задаётся в settings_prod.
ADMIN_ALLOWED_HOSTS = None

# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    'https://new.tir-lugansk.ru',
    'https://tir-lugansk.ru',
    'http://45.130.42.65:8000',
    'http://localhost:8000',
]

# Защита cookies и сессий (без перегрузки)
SESSION_COOKIE_HTTPONLY = True   # Доступ к sessionid только по HTTP, не из JS
SESSION_COOKIE_SAMESITE = 'Lax'  # Защита от CSRF через cookie в сторонних запросах
CSRF_COOKIE_SAMESITE = 'Lax'
# В продакшене (settings_prod) дополнительно: SESSION_COOKIE_SECURE, CSRF_COOKIE_SECURE


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Красивая админка
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'ckeditor',
    'ckeditor_uploader',
    'shop',
    'pages',
]

MIDDLEWARE = [
    'tir_lugansk.middleware.AllowHttpForAdminHostsMiddleware',  # HTTP для админки по IP (редирект HTTPS только для домена)
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Добавляем whitenoise
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tir_lugansk.middleware.AdminOnlyFromAllowedHostsMiddleware',  # админка только по IP (см. settings_prod)
]

ROOT_URLCONF = 'tir_lugansk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.nav_root_categories',
                'pages.context_processors.header_notice',
            ],
        },
    },
]

WSGI_APPLICATION = 'tir_lugansk.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# PostgreSQL. Параметры в .env: DB_NAME, DB_USER, DB_PASSWORD, DB_HOST, DB_PORT (см. env.example).
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', ''),
        'USER': os.environ.get('DB_USER', ''),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'CONN_MAX_AGE': 60,
        'OPTIONS': {'sslmode': 'disable'},
    }
}
# Cache Configuration
# Используем локальную память (для продакшена рекомендуется Redis/Memcached)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'tir-lugansk-cache',
        'TIMEOUT': 300,  # 5 минут по умолчанию
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# Кеширование категорий и брендов (обновляется редко)
CATEGORY_CACHE_TIMEOUT = 3600  # 1 час
BRAND_CACHE_TIMEOUT = 3600  # 1 час
PRODUCT_CACHE_TIMEOUT = 300  # 5 минут

# Email notifications (call request / price inquiry)
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', '1') == '1'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', '0') == '1'
DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL',
    EMAIL_HOST_USER or 'no-reply@tir-lugansk.ru',
)
SERVER_EMAIL = os.environ.get('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

_notification_emails_raw = os.environ.get(
    'NOTIFICATION_EMAIL_RECIPIENTS',
    'astbackend@yandex.ru',
)
NOTIFICATION_EMAIL_RECIPIENTS = [
    email.strip()
    for email in _notification_emails_raw.split(',')
    if email.strip()
]

# Telegram notifications
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '')
TELEGRAM_CHAT_ID = os.environ.get('TELEGRAM_CHAT_ID', '')

# MAX notifications
MAX_BOT_TOKEN = os.environ.get('MAX_BOT_TOKEN', '')
MAX_OWNER_ID = os.environ.get('MAX_OWNER_ID', '')
MAX_API_BASE_URL = os.environ.get('MAX_API_BASE_URL', 'https://api.max.ru')

# Celery (async notifications queue)
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'))
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 60
CELERY_TASK_ALWAYS_EAGER = os.environ.get('CELERY_TASK_ALWAYS_EAGER', '0') == '1'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # Основная папка static для админских файлов
    BASE_DIR / 'templates' / 'assets',  # Папка assets для фронтенда
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Статические sitemap (cron: manage.py build_sitemaps)
SITEMAP_OUTPUT_DIR = Path(os.environ.get('SITEMAP_OUTPUT_DIR', str(BASE_DIR / 'sitemaps')))
SITEMAP_CANONICAL_DOMAIN = os.environ.get('SITEMAP_CANONICAL_DOMAIN', 'tir-lugansk.ru')
SITEMAP_USE_HTTPS = os.environ.get('SITEMAP_USE_HTTPS', '1') == '1'
SITEMAP_STATIC_ENABLED = os.environ.get('SITEMAP_STATIC_ENABLED', '1') == '1'

# Whitenoise settings
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Кеширование статики в браузере (п. 3.3, 5.1). Для медиа — настраивать Cache-Control в nginx/прокси.
WHITENOISE_MAX_AGE = 86400  # 1 день; при collectstatic с хешами в именах файлов можно увеличить

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CKEditor (WYSIWYG в админке для HTML-полей страниц и материалов «Полезное»)
CKEDITOR_UPLOAD_PATH = 'ckeditor/'
CKEDITOR_IMAGE_BACKEND = 'pillow'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'tir_default',
        'toolbar_tir_default': [
            ['Bold', 'Italic', 'Underline', 'Strike', '-', 'RemoveFormat'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent'],
            ['JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink', 'Anchor'],
            ['Image', 'Table', 'HorizontalRule'],
            ['Format', 'FontSize'],
            ['TextColor', 'BGColor'],
            ['Maximize', 'ShowBlocks', 'Source'],
        ],
        'height': 360,
        'width': '100%',
        'language': 'ru',
    },
}

# Папка, куда администратор копирует файлы по SFTP/rsync для импорта изображений.
# Локально: проект/incoming_images. На сервере: задайте свой путь через переменную окружения INCOMING_IMAGES_DIR.
INCOMING_IMAGES_DIR = Path(os.environ.get('INCOMING_IMAGES_DIR', str(BASE_DIR / 'incoming_images')))

# Watermark settings for imported product images.
WATERMARK_ENABLED = os.environ.get('WATERMARK_ENABLED', '0')
WATERMARK_IMAGE_PATH = os.environ.get('WATERMARK_IMAGE_PATH', str(BASE_DIR / 'staticfiles' / 'img' / 'logo_footer.png'))
WATERMARK_SCALE = float(os.environ.get('WATERMARK_SCALE', '0.22'))
WATERMARK_OPACITY = float(os.environ.get('WATERMARK_OPACITY', '0.18'))
WATERMARK_MARGIN = int(os.environ.get('WATERMARK_MARGIN', '16'))
WATERMARK_POSITION = os.environ.get('WATERMARK_POSITION', 'center')
WATERMARK_FIT_MODE = os.environ.get('WATERMARK_FIT_MODE', 'full')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Админка / CKEditor: большие HTML-страницы (Django по умолчанию — 2.5 МБ).
# На сервере в nginx тоже нужно: client_max_body_size 50M;
DATA_UPLOAD_MAX_MB = int(os.environ.get('DATA_UPLOAD_MAX_MB', '50'))
DATA_UPLOAD_MAX_MEMORY_SIZE = DATA_UPLOAD_MAX_MB * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = DATA_UPLOAD_MAX_MB * 1024 * 1024
# Много полей в форме админки (инлайны, CKEditor)
DATA_UPLOAD_MAX_NUMBER_FIELDS = int(os.environ.get('DATA_UPLOAD_MAX_NUMBER_FIELDS', '10000'))

# Jazzmin settings
JAZZMIN_SETTINGS = {
    "site_title": "TIR Lugansk",
    "site_header": "TIR Lugansk",
    "site_brand": "TIR Lugansk",
    "site_logo": None,
    "welcome_sign": "Добро пожаловать в админку TIR Lugansk",
    "copyright": "TIR Lugansk Ltd",
    "search_model": ["shop.Product", "shop.Category"],
    "user_avatar": None,
    "show_sidebar": True,
    "navigation_expanded": True,
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "shop.Product": "fas fa-box",
        "shop.Category": "fas fa-tags",
        "shop.Brand": "fas fa-industry",
        "pages.Page": "fas fa-file-alt",
        "pages.Contact": "fas fa-phone",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": "admin/css/responsive_sidebar.css",
    "custom_js": "admin/js/responsive_sidebar.js",
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-teal",
    "navbar": "navbar-dark",
    "no_navbar_brand": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-success",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cosmo",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# Logging configuration
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'audit': {
            'format': '{asctime} | {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'django.log',
            'formatter': 'verbose',
        },
        'audit_file': {
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'audit.log',
            'formatter': 'audit',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'shop': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'audit': {
            'handlers': ['audit_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
