# Generated by Django 6.0 on 2026-02-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_brand_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importfile',
            name='file',
            field=models.FileField(upload_to='imports/', verbose_name='Файл импорта (CSV/DBF)'),
        ),
    ]
