# Generated by Django 4.2.28 on 2026-02-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_add_file_validation_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='oekod',
            new_name='shop_oekod_oe_kod__ef6b2c_idx',
            old_name='shop_oekod_oe_kod__a70d36_idx',
        ),
        migrations.RenameIndex(
            model_name='oekod',
            new_name='shop_oekod_oe_kod_61c6c7_idx',
            old_name='shop_oekod_oe_kod_8bca5e_idx',
        ),
        migrations.RenameIndex(
            model_name='oekod',
            new_name='shop_oekod_id_oe_f2d217_idx',
            old_name='shop_oekod_id_oe_fef2b0_idx',
        ),
        migrations.RenameIndex(
            model_name='oekod',
            new_name='shop_oekod_id_tova_bddd4e_idx',
            old_name='shop_oekod_id_tova_c73f9b_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='artikyl_number_clean',
            field=models.CharField(blank=True, db_index=True, help_text='Автоматически генерируется без пробелов и знаков препинания', max_length=100, verbose_name='Дополнительный номер (очищенный)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='catalog_number_clean',
            field=models.CharField(blank=True, db_index=True, help_text='Автоматически генерируется без пробелов и знаков препинания', max_length=50, verbose_name='Каталожный номер (очищенный)'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['catalog_number_clean'], name='shop_produc_catalog_150f83_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['artikyl_number_clean'], name='shop_produc_artikyl_7a7029_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tmp_id'], name='shop_produc_tmp_id_3ea738_idx'),
        ),
    ]
