# Generated by Django 4.2.26 on 2026-02-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_shop_oekod_oe_kod__a70d36_idx_shop_oekod_oe_kod__ef6b2c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='meta_description',
            field=models.TextField(blank=True, max_length=320, verbose_name='SEO описание'),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO ключевые слова'),
        ),
        migrations.AddField(
            model_name='brand',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, max_length=320, verbose_name='SEO описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO ключевые слова'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, max_length=320, verbose_name='SEO описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO ключевые слова'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок'),
        ),
        migrations.AlterField(
            model_name='importfile',
            name='file_type',
            field=models.CharField(blank=True, choices=[('brands', 'Бренды (ID_BRENB, NAME)'), ('products', 'Товары (TMP_ID, PROPERTY_P, PROPERTY_T)'), ('analogs', 'OE Аналоги (ID_OE, ID_TOVAR, ID_BRENB)')], help_text='Выберите тип импортируемых данных', max_length=20, null=True, verbose_name='Тип файла'),
        ),
    ]
