# Generated by Django 4.2.28 on 2026-02-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_fix_id_oe_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе'),
        ),
    ]
