# Generated by Django 4.2.28 on 2026-03-25 00:09

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_add_product_in_stock_catalog_clean_index'),
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AddIndex(
            model_name='brand',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='shop_brand_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='oekod',
            index=django.contrib.postgres.indexes.GinIndex(fields=['oe_kod_clean'], name='shop_oekod_clean_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='oekod',
            index=django.contrib.postgres.indexes.GinIndex(fields=['oe_kod'], name='shop_oekod_kod_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['in_stock', 'category'], name='shop_prod_stock_catid_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['in_stock', 'brand'], name='shop_prod_stock_brid_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['in_stock', 'price'], name='shop_prod_stock_price_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='shop_prod_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['catalog_number_clean'], name='shop_prod_catcl_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['artikyl_number_clean'], name='shop_prod_artcl_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['cross_number'], name='shop_prod_cross_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
